name: Build with Versioneer
on:
  push:
    tags:
      - 'v*'  # Wird ausgeführt, wenn du ein neues Tag wie "v1.0" erstellst

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Specify your desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install versioneer
          pip install -e .  # Install your project in editable mode

      - name: Create Versioneer build
        run: |
          python setup.py sdist bdist_wheel  # This will create the distributable packages with the Versioneer-generated version

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-package-distributables
          path: dist/

